braun/apps/inicio/urls.py
from django.conf.urls import patterns, include, url
from .views import *
urlpatterns = patterns('',
	url(r'^$', inicio),
    url(r'^loguin/$', loguin),

    url(r'^docentes/$', docentes),
    url(r'^privado/$', privado),
    url(r'^salir/$', salir),
    url(r'^editarperfil/$',editar_perfil),
    url(r'^nuevo/$',nuevoUser.as_view(), name='nuevoUser'),
    url(r'^DatosUsuario/$', DatosUsuario, name='listaUsuarios'),
    url(r'^verificacion/$',verificacion, name='verificacion'),
    url(r'^imprimirHistorial/(?P<id>\d+)/$', imprimirHistorial),
    url(r'^PlanBimestral/$', PlanBimestral),
    url(r'^verPlanBimestral/$', verPlanBimestral),
    url(r'^newAvanse/$', newAvanse),
    url(r'^verAvances/$', verAvances),
    url(r'^nuevoDirector/$',nuevoDirector.as_view(), name='nuevoDirector'),
    url(r'^verDitectores/$', verDitectores, name='verDitectores'),

    url(r'^nuevoAlumno/$',nuevoAlumno.as_view(), name='nuevoAlumno'),
    url(r'^verAlumno', verAlumno, name='verAlumno'),
    url(r'^info/(?P<id>\d+)/$',Informacion),
    url(r'^NewAntecedente/$', NewAntecedente),
    url(r'^VerAntecedente/$', VerAntecedente),
    url(r'^buscarAlumno/$', buscarAlumno),
    url(r'^escogido/(?P<id>\d+)/$', escogido),
    url(r'^misAntecedentes/(?P<id>\d+)/$', VerAntecedente),
    url(r'^verHistorial/(?P<id>\d+)/$', verHistorial),
    url(r'^Darbaja/(?P<id>\d+)/$', Darbaja),
    url(r'^DarAlta/(?P<id>\d+)/$', DarAlta),
    url(r'^AltaAlumno/(?P<id>\d+)/$', AltaAlumno),
    url(r'^AlumnoVerDaja/(?P<id>\d+)/$', Darbaja),
    url(r'^DelAlumno/(?P<id>\d+)/$', DelAlumno),
    url(r'^AlumnoVerAlta/(?P<id>\d+)/$', DarAlta),
    url(r'^EditAlumno/(?P<id>\d+)/$', EditAlumno),
    url(r'^BajaAntecedente/(?P<id>\d+)/$', BajaAntecedente),
    url(r'^DelAntecedentes/(?P<id>\d+)/$', DelAntecedentes),
    url(r'^AltaAntecedente/(?P<id>\d+)/$', AltaAntecedente),
    url(r'^bajaAntecendetes/(?P<id>\d+)/$', bajaAntecendetes),
    url(r'^editAnte/(?P<id>\d+)/$', editAnte),
    url(r'^DarbajaDocente/(?P<id>\d+)/$', DarbajaDocente),
    url(r'^Deletedocente/(?P<id>\d+)/$', Deletedocente),
    url(r'^DarAltaDocente/(?P<id>\d+)/$', DarAltaDocente),
    url(r'^Altadocentes/(?P<id>\d+)/$', Altadocentes),
    url(r'^Canbiodirector/(?P<id>\d+)/$', Canbiodirector),
    url(r'^buscar/$', buscar),
    url(r'^nuevoAlumnoA/$', nuevoAlumnoA),
    url(r'^verHistoriales/$', verHistoriales),
    url(r'^por_curso/$', por_curso),
)

braun/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'braun.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include("braun.apps.inicio.urls")),

    url(r'^media/(?P<path>.*)$','django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}
        ),

)

braun/apps/inicio/models.py
#encoding:utf-8
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.forms import User
# Create your models here.
class Perfiles(models.Model):
	usuario = models.OneToOneField(User, unique=True, related_name='perfil')
	materno = models.CharField(max_length=50)
	ci = models.IntegerField()
	telefono = models.IntegerField()
	def __unicode__(self):
		return self.usuario.username
class Bismestre(models.Model):
	bimestre = models.IntegerField()
	titulo = models.CharField(max_length=50)
	descripcion = models.TextField(blank=True, null=True)
	archivo = models.FileField(upload_to = 'bimestres')
	docente = models.ForeignKey(User)
	fecha_registro=models.DateTimeField(auto_now=True)
	estado = models.BooleanField(default=True)
	def __unicode__(self):
		return self.titulo
class Avanse(models.Model):
	titulo = models.CharField(max_length=50)
	descripcion = models.TextField(blank=True, null=True)
	materia = models.CharField(max_length=50)
	docente = models.ForeignKey(User)
	archivo = models.FileField(upload_to = 'avanses')
	estado = models.BooleanField(default=True)
	fecha_registro=models.DateTimeField(auto_now=True)
	def __unicode__(self):
		return self.titulo
class Curso(models.Model):
	usuario = models.ForeignKey(User)
	curso = models.CharField(max_length=50)
	fecha_registro=models.DateTimeField(auto_now=True)
	estado=models.BooleanField(default=True)
	def __unicode__(self):
		return self.curso

class Alumnos(models.Model):
	usuario = models.OneToOneField(User, unique=True, related_name='perfilAlumno')
	materno = models.CharField(max_length=50)
	curso = models.ForeignKey(Curso)
	ci = models.IntegerField(blank=True,null=True)
	telefono = models.IntegerField(blank=True,null=True)
	def __unicode__(self):
		return "%s"%(self.ci)
class Directores(models.Model):
	usuario = models.OneToOneField(User, unique=True, related_name='perfilDirector')
	materno = models.CharField(max_length=50)
	ci = models.IntegerField()
	telefono = models.IntegerField()
	def __unicode__(self):
		return self.usuario.username
class antecedentes(models.Model):
	usuario=models.ForeignKey(User)
	alumno=models.ForeignKey(Alumnos)
	asunto=models.CharField(max_length=50)
	descripcion=models.TextField()
	fecha_registro=models.DateTimeField(auto_now=True)
	estado=models.BooleanField(default=True)
	def __unicode__(self):
		return self.alumno.materno

braun/apps/inicio/forms.py
#encoding:utf-8
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import *
from .forms import *
from django.contrib.auth.forms import User
class UserForm(UserCreationForm):
	username = forms.CharField(max_length=40,required=True,label="Nombre de Usuario *")
	password1 = forms.CharField(required=True,label="Contraseña *",widget=forms.PasswordInput(render_value=False))
	password2 = forms.CharField(required=True, label="Confirmación *",widget=forms.PasswordInput(render_value=False))
	first_name = forms.CharField(max_length=40,required=True, label="Nombre Completo *")
	last_name = forms.CharField(max_length=50,required=True, label="Ap. Paterno *")
	materno = forms.CharField(max_length=50,required=True,label="Ap. Materno *")
	email = forms.EmailField(required=False,label='Correo Electrónico')
	ci = forms.IntegerField(required=True,label="Nro. de CI. *")
	telefono = forms.IntegerField(required=True,label="Teléfono/Celular *")
	def clean_ci(self):
		ci=self.cleaned_data['ci']
		if len(str(ci))>8 or len(str(ci))<=5:
			raise forms.ValidationError('El Nro. de CI. deve ser 6 dígitos')
		try:
			p=Perfiles.objects.get(ci=ci)
		except Perfiles.DoesNotExist:
			return ci
		raise forms.ValidationError('El Nro. de CI. ya Existe')
	def clean_telefono(self):
		telefono=self.cleaned_data['telefono']
		if len(str(telefono))>9 or len(str(telefono))<=7:
			raise forms.ValidationError('El Nro. de Teléfono deve ser 8 dígitos')
		try:
			p = Perfiles.objects.get(telefono=telefono)
		except Perfiles.DoesNotExist:
			return telefono
		raise forms.ValidationError('El Numero de Teléfono ya Existe')
	# def clean_email(self):
	# 	email=self.cleaned_data['email']
	# 	try:
	# 		p = User.objects.get(email=email)
	# 	except User.DoesNotExist:
	# 		return email
	# 	raise forms.ValidationError('El Correo electronico no deve ser Repetido')
	class Meta:
		model=User
		fields=("username","password1","password2","first_name","last_name","materno","ci","telefono","email")
		widgets = {
			'password1':forms.PasswordInput(),
		}
	def save(self,commit=True):
		user=super(UserForm,self).save(commit=False)
		user.first_name=self.cleaned_data.get("first_name")
		user.last_name=self.cleaned_data.get("last_name")
		user.email=self.cleaned_data.get('email')
		if commit:
			user.is_staff = True
			user.is_active = False
			user.save()
		return user
#######################################Director
class UserFormDirector(UserCreationForm):
	username = forms.CharField(max_length=40,label="Nombre de Usuario *")
	password1 = forms.CharField(label="Contraseña *",widget=forms.PasswordInput(render_value=False))
	password2 = forms.CharField(label="Confirmación *",widget=forms.PasswordInput(render_value=False))
	first_name = forms.CharField(max_length=40, label="Nombre Completo *")
	last_name = forms.CharField(max_length=50, label="Ap. Paterno *")
	materno = forms.CharField(max_length=50,label="Ap. Materno *")
	email = forms.EmailField(label='Correo Electrónico')
	ci = forms.IntegerField(label="Nro. de CI. *")
	telefono = forms.IntegerField(label="Teléfono/Celular *")
	def clean_ci(self):
		ci=self.cleaned_data['ci']
		if len(str(ci))>8 or len(str(ci))<=5:
			raise forms.ValidationError('El Nro. de CI. deve ser 6 dígitos')
		try:
			p=Directores.objects.get(ci=ci)
		except Directores.DoesNotExist:
			return ci
		raise forms.ValidationError('El Nro. de CI. ya Existe')
	def clean_telefono(self):
		telefono=self.cleaned_data['telefono']
		if len(str(telefono))>9 or len(str(telefono))<=7:
			raise forms.ValidationError('El Nro. de Teléfono deve ser 8 dígitos')
		try:
			p = Directores.objects.get(telefono=telefono)
		except Directores.DoesNotExist:
			return telefono
		raise forms.ValidationError('El Numero de Teléfono ya Existe')
	class Meta:
		model=User
		fields=("username","password1","password2","first_name","last_name","materno","ci","telefono","email")
		widgets = {
			'password1':forms.PasswordInput(),
		}
	def save(self,commit=True):
		user=super(UserFormDirector,self).save(commit=False)
		user.first_name=self.cleaned_data.get("first_name")
		user.last_name=self.cleaned_data.get("last_name")
		user.email=self.cleaned_data.get('email')
		if commit:
			user.is_staff = False
			user.is_active = False
			user.is_superuser = True
			user.save()
		return user
##### Alumno
class UserFormAlumno(UserCreationForm):
	username = forms.CharField(max_length=40,required=False,label="Nombre de Usuario *")
	password1 = forms.CharField(required=False,label="Contraseña *",widget=forms.PasswordInput(render_value=False))
	password2 = forms.CharField(required=False, label="Confirmación *",widget=forms.PasswordInput(render_value=False))
	first_name = forms.CharField(max_length=40,required=True, label="Nombre Completo *")
	last_name = forms.CharField(max_length=50,required=True, label="Ap. Paterno *")
	materno = forms.CharField(max_length=50,required=True,label="Ap. Materno *")
	email = forms.EmailField(required=False,label='Correo Electrónico')
	#curso = forms.CharField(curso=Curso.objects.all())
	ci = forms.IntegerField(required=False,label="Nro. de CI. *")
	telefono = forms.IntegerField(required=False,label="Teléfono/Celular:")
	def clean_ci(self):
		ci=self.cleaned_data['ci']
		if len(str(ci))>7 or len(str(ci))<=5:
			raise forms.ValidationError('El Nro. de CI. deve ser 6 dígitos')
		try:
			p=Directores.objects.get(ci=ci)
		except Directores.DoesNotExist:
			return ci
		raise forms.ValidationError('El Nro. de CI. ya Existe')
	class Meta:
		model=User
		fields=("username","password1","password2","first_name","last_name","materno","ci","telefono","email")
		widgets = {
			'password1':forms.PasswordInput(),
		}
	def save(self,commit=True):
		user=super(UserFormAlumno,self).save(commit=False)
		user.first_name=self.cleaned_data.get("first_name").capitalize()
		user.last_name=self.cleaned_data.get("last_name").capitalize()
		user.email=self.cleaned_data.get('email')
		if commit:
			user.save()
		return user


#formularios para editar el usuario
class formPerfiles(forms.ModelForm):
	class Meta:
		model=Perfiles
		exclude=['usuario']
class UserForms(forms.ModelForm):
	class Meta:
		model=User
		fields = ('username','first_name','last_name','email')

class FormEdirAlum(forms.ModelForm):
	class Meta:
		model=Alumnos
		exclude=['usuario']
class FormEditUser(forms.ModelForm):
	class Meta:
		model=User
		fields = ('first_name','last_name','email')

bim = (('', 'Indique el Bimestre',),('1', 'Bimestre 1',), ('2', 'Bimestre 2',),('3', 'Bimestre 3',),('4','Bimestre 4',))
class FormBimestre(forms.ModelForm):
	bimestre=forms.ChoiceField(widget=forms.Select, choices=bim, label="Bimestre *")
	titulo = forms.CharField(max_length=40,required=True,label="Título *")
	descripcion = forms.CharField(widget=forms.Textarea,required=False,label="Descripción:")
	archivo = forms.FileField(label="Archivo *")
	class Meta:
		model=Bismestre
		exclude=['docente','estado']
bim = (('', 'Indique la Materia',), ('Computacion', 'Computacion',),('Educación Fisica', 'Educación Fisica',),('Matemáticas','Matemáticas',),('Fisica','Fisica',),('Quimica','Quimica',))
class FormAvanse(forms.ModelForm):
	titulo=forms.CharField(max_length=40,required=True,label="Título *")
	descripcion=forms.CharField(widget=forms.Textarea,required=False,label="Descripción:")
	materia=forms.ChoiceField(widget=forms.Select, choices=bim, label="Materia *")
	archivo=forms.FileField(label="Archivo *")
	class Meta:
		model=Avanse
		exclude=['docente','estado']

class FormAnte(forms.ModelForm):
	class Meta:
		model=antecedentes
		exclude=['usuario','alumno','fecha_registro','estado']


class Alumnoforms(forms.ModelForm):
	class Meta:
		model = User
		exclude=['groups','user_permissions','is_superuser','is_staff','is_active','last_login','date_joined']
class formPerfil(forms.ModelForm):
	class Meta:
		model = Alumnos
		exclude=['usuario','telefono']

braun/templates/administrador/DatosDirectores.html
<div class="table-responsive">
<table class="table table-hover table-striped">
	<tr><td colspan="10" align="center">LISTA DE DIRECTORES EN EL SISTEMA</td></tr>
		<tr class="success">
			<td>Usuario</td>
			<td>Nombre</td>
			<td>Ap. Paterno</td>
			<td>Ap. Materno</td>
			<td>Nro. CI.</td>
			<td>E-mail</td>
			<td>Teléfono</td>
			<td>Fecha y hora registro</td>
			<td>Estado</td>
		</tr>
{% for j in users %}
	{% for i in perfil %}
			{% if j.id == i.usuario_id %}
<tr>
	<td>{{j.username}}</td>
	<td>{{j.first_name|upper}}</td>
	<td>{{j.last_name|upper}}</td>
	<td>{{i.materno|upper}}</td>
	<td>{{i.ci}}</td>
	<td>{{j.email}}</td>
	<td>{{i.telefono}}</td>
	<td>{{j.date_joined}}</td>
	<td>
	{% if j.is_superuser %}
			<span><img src="/static/img/icon_success.gif"></span>
		{% else %}
			<span><img src="/static/img/icon_error.gif"></span>
	{% endif %}
	</td>
</tr>
			{% endif %}
		{% endfor %}
	{% endfor %}
	<tr>
		<td>Usuarios:{{t_user}}</td>
	</tr>
	</table>
</div>

braun/templates/administrador/nuevoAlumno.html
<div class="card">
    <p id="texto">Registrar Nuevo Alumno</p>
    <span>Todos los campos con (*) son requeridos</span>
 <form method="POST" id="Tipo" onsubmit="return verificar()"> 
   {% csrf_token %}
    <!-- <label for="id_password">Contraseña:</label> -->
    <input id="id_password" maxlength="128" name="password" type="text">
<!-- <label for="id_username">Nombre de usuario:</label> -->
<input id="id_username" maxlength="30" name="username" type="text"><br>
<label for="id_first_name">Nombres (*):</label>
<input id="id_first_name" maxlength="50" name="first_name" type="text" required>
<label for="id_last_name">Ap. Paterno (*):</label>
<input id="id_last_name" maxlength="30" name="last_name" type="text" required>
<label for="id_materno">Ap. Materno (*):</label>
<input id="id_materno" maxlength="30" name="materno" type="text" required>
<label for="id_curso">Curso (*):</label>
    <select id="id_curso" name="curso" required>
        <option value="" selected="selected">---------</option>
        {% for i in cursos %}
        <option value="{{i.id}}"> {{i.curso|upper}} </option>
        {% endfor %}
    </select>
<label for="id_ci">Ci (*):</label>
<input id="id_ci" name="ci" type="number" required>
<!-- <label for="id_telefono">Telefono:</label> -->
<input id="id_telefono" name="telefono" type="number" value="0">

<label for="id_email">Dirección de correo electrónico:</label>
<input id="id_email" maxlength="75" name="email" type="email">
    <button class="btn btn-success" type="submit" onsubmit="verificar()">Aceptar</button>
  </form>
  <p id="valid" style="color:red; text_align:center;"></p>
</div>
<script type="text/javascript">
$('#id_ci').blur(ejecutar);
        function ejecutar(){
            var use= $('#id_ci').val();
            $.ajax({
                type:'get',
                url:'/verificacion/',
                data:{'use': use },
                beforeSend: entesEnviar,
                success:function (resp){
                    console.log(resp);
                    $("#valid").html(resp);
                }
            });
            function entesEnviar(){
                $('#valid').text("Verificando...")
            }
        }
$("#id_ci").blur(Convalidar);
function Convalidar(){
    $("#id_username").val($("#id_ci").val());
    $("#id_password").val($("#id_ci").val());
    $("#id_password2").val($("#id_ci").val());
}

    function verificar(){
        
        var nombre=$('#id_first_name').val();
        var ape=$('#id_last_name').val();
        if (nombre==''||ape==''){
            alert('Error no deve dejar casillas en blanco');
            return false;
        }
        else{
           
        }
    }
    $('#Tipo').submit(function(e){
        e.preventDefault();
        var dato=$(this).serialize();
        console.log(dato);
        $.ajax({
            type:'POST',
            url:'/nuevoAlumnoA/',
            data: dato,
            success:function(resp){
                console.log(resp);
                $('#FormAjax').html(resp);
            }
        });
    });
$(function(){
    document.getElementById("id_first_name").focus();
    $(".helptext").hide();
    $("#id_password").hide();
    $("#id_username").hide();
    $("#id_telefono").hide();
});
</script>

braun/templates/administrador/nuevoDirector.html
<script type="text/javascript">
$('#id_username').blur(ejecutar);
        function ejecutar(){
            var use= $('#id_username').val();
            $.ajax({
                type:'get',
                url:'/verificacion/',
                data:{'use': use },
                beforeSend: entesEnviar,
                success:function (resp){
                    console.log(resp);
                    $('#valid').html(resp);
                }
            });
            function entesEnviar(){
                $('#valid').text("Verificando...")
            }
        }
    $('#TipoD').submit(function(e){
        e.preventDefault();
        var dato=$(this).serialize();
        console.log(dato);
        $.ajax({
            type:'POST',
            url:'/nuevoDirector/',
            data: dato,
            success:function(resp){
                console.log(resp);
                $('#FormAjax').html(resp);
                Canbiodirector();
            }
        });
    });
    function Canbiodirector(){
            $.ajax({
                type:'GET',
                url:'/Canbiodirector/'+{{user.id}}+'/',
                success:function(resp){
                    $('#DatosContenidos').html(resp);
                    alert(resp)
                    VerProveedores();
                }
            });
        }
</script>
<div class="card">
    <p id="texto"><strong>Registrar Nuevo Director</strong><br>
        <span style="color:red;">Nota: Si usted registra un nuevo director su cuenta actual será dado de baja, ya que el sistema no permitirá tener dos cuentas de director.</span></p>
    <span>Todos los campos con (*) son requeridos</span>
 <form method="POST" id="TipoD" > {% csrf_token %}
    <li style="text-align: center;">Datos de tu cuenta</li>
<label for="id_username">Nombre de Usuario *:</label>
    <input id="id_username" placeholder="Ejem. jjavierl" maxlength="40" name="username" type="text" required>
<label for="id_password1">Contraseña *:</label>
    <input id="id_password1" placeholder="Contraseña" name="password1" type="password" required>
<label for="id_password2">Confirmación *:</label>
    <input id="id_password2" placeholder="Confirmación" name="password2" type="password" required>
    <li style="text-align: center;">Datos Personales</li>
<label for="id_first_name">Nombre Completo *:</label>
    <input id="id_first_name" placeholder="Nombre Completo" maxlength="40" name="first_name" type="text" required>
<label for="id_last_name">Ap. Paterno *:</label>
    <input id="id_last_name" placeholder="Apellido Paterno" maxlength="50" name="last_name" type="text" required>
<label for="id_materno">Ap. Materno *:</label>
    <input id="id_materno" placeholder="Apellido Materno" maxlength="50" name="materno" type="text" required>
<label for="id_ci">Nro. de CI. *:</label><input id="id_ci" placeholder="Nro. de CI." maxlength="6" name="ci" type="number">
<label for="id_telefono">Teléfono/Celular *:</label>
    <input id="id_telefono" placeholder="Ejem. 78100000" maxlength="8" name="telefono" type="number" required>
<label for="id_email">Correo Electrónico:</label>
    <input id="id_email" placeholder="Ejem. jjavier@gmail.com" name="email" type="email"><br>
    <button class="btn btn-success" type="submit">Guardar</button>
  </form>
  <p id="valid" style="color:red; text_align:center;"></p>
</div> 

braun/templates/administrador/por_curso.html
<table class="table table-hover table-striped">
	<tr><td colspan="8" align="center">LISTA DE MEMORANDUM EN EL SISTEMA - GESTIÓN: {% now "Y" %}</td></tr>
		<tr class="success">
			<td>Cod</td>
			<td>Nombre Alumno</td>
			<td>Asunto</td>
			<td>Descripción</td>
			<td>Fecha y hora de Registro</td>
			<td>Registrado Por:</td>
			<td>Estado</td>
		</tr>
{% for j in historiales %}
	{% for i in alumnos %}
		{% for k in usuarios %}
			{% if j.alumno.id == i.id and i.usuario.id == k.id %}
			<tr>
				<td><a href="/escogido/{{i.usuario.id }}/" id="es">
					<span class="glyphicon glyphicon-chevron-right"></span></a> 
					{{j.id}}</td>
				<td>{{k.get_full_name|upper}} {{i.materno|upper}}</td>
				<td>{{j.asunto|upper}}</td>
				<td>{{j.descripcion}}</td>
				<td>{{j.fecha_registro}}</td>
				<td>{{j.usuario.get_full_name|upper}}</td>
				<td>
				{% if j.estado %}
						<span><img src="/static/img/icon_success.gif"></span>
					{% else %}
						<span><img src="/static/img/icon_error.gif"></span>
				{% endif %}
				</td>
			</tr>
			{% endif %}
		{% endfor %}		
	{% endfor %}		
{% endfor %}
	<tr>
		<td></td><td>Registrados:{{t_his}}</td>
	</tr>
	</table>
	<ul class="pager">
		 <span class="current">
            Página 1 de 1.
        </span>
	</ul>
<script type="text/javascript">
	$(".table tr td #es").on("click",function(e){
		e.preventDefault();
			$.ajax({
				type:'GET',
				url:$(this).attr("href"),
				beforeSend:Espera,
				success:function(resp){
					$("#FormAjax").html(resp);
				}
			});
			 function Espera(){
		      $("#FormAjax").html('<img src="/static/img/log.gif" id="icono"></img><br>Procesando...');
		    }
	});
</script>

braun/templates/administrador/verAlumno.html
<div class="table-responsive">
<table class="table table-hover table-striped">
	<tr><td colspan="8" align="center">LISTA DE ALUMNOS EN EL SISTEMA</td></tr>
		<tr class="success">
			<td>Nombre(s)</td>
			<td>Ap. Paterno</td>
			<td>Ap. Materno</td>
			<td>Curso</td>
			<td>Nro. CI.</td>
			<td>Teléfono</td>
			<td>Estado</td>
		</tr>
{% for j in contenido %}
<tr>
	<td><a href="/escogido/{{j.id}}/" id="es"><span class="glyphicon glyphicon-chevron-right"></span></a> 
		{{j.first_name|upper}}</td>
	<td>{{j.last_name|upper}}</td>
	<td>{{j.perfilAlumno.materno|upper}}</td>
	<td>{{j.perfilAlumno.curso}}</td>
	<td>{{j.perfilAlumno.ci}}</td>
	<td>{{j.perfilAlumno.telefono}}</td>
	<td>
	{% if j.is_active %}
			<span><img src="/static/img/icon_success.gif"></span>
		{% else %}
			<span><img src="/static/img/icon_error.gif"></span>
	{% endif %}
	</td>
</tr>
		
		
{% endfor %}
	<tr>
		<td>Usuarios:{{t_user}}</td>
	</tr>
	</table>
	<ul class="pager">
		{% if contenido.has_previous %}
			  <li><a href="/verAlumno/?page={{ contenido.previous_page_number }}">Anterior</a></li>
		{% endif %}
		 <span class="current">
            Página {{ contenido.number }} de {{ contenido.paginator.num_pages }}.
        </span>
        {% if contenido.has_next %}
			  <li><a href="/verAlumno/?page={{ contenido.next_page_number }}">Siguiente</a></li>
		{% endif %}
	</ul>
</div>
<script type="text/javascript">
	$(".table tr td #es").on("click",function(e){
		e.preventDefault();
			$.ajax({
				type:'GET',
				url:$(this).attr("href"),
				beforeSend:Espera,
				success:function(resp){
					$("#FormAjax").html(resp);
				}
			});
			 function Espera(){
		      $("#FormAjax").html('<img src="/static/img/log.gif" id="icono"></img><br>Procesando...');
		    }
	});
	$(".pager li a").on("click",function(e){
		e.preventDefault();
			$.ajax({
					type:'GET',
					url:$(this).attr("href"),
					beforeSend:Espera,
					success:function(resp){
						$("#FormAjax").html(resp);
					}
			});
			 function Espera(){
		      $("#FormAjax").html('<img src="/static/img/log.gif" id="icono"></img><br>Procesando...');
		    }
	});
</script>