braun/apps/inicio/urls.py
from django.conf.urls import patterns, include, url
from .views import *
urlpatterns = patterns('',
	url(r'^$', inicio),
    url(r'^loguin/$', loguin),

    url(r'^docentes/$', docentes),
    url(r'^privado/$', privado),
    url(r'^salir/$', salir),
    url(r'^editarperfil/$',editar_perfil),
    url(r'^nuevo/$',nuevoUser.as_view(), name='nuevoUser'),
    url(r'^DatosUsuario/$', DatosUsuario, name='listaUsuarios'),
    url(r'^verificacion/$',verificacion, name='verificacion'),
    url(r'^imprimirHistorial/(?P<id>\d+)/$', imprimirHistorial),
    url(r'^PlanBimestral/$', PlanBimestral),
    url(r'^verPlanBimestral/$', verPlanBimestral),
    url(r'^newAvanse/$', newAvanse),
    url(r'^verAvances/$', verAvances),
    url(r'^nuevoDirector/$',nuevoDirector.as_view(), name='nuevoDirector'),
    url(r'^verDitectores/$', verDitectores, name='verDitectores'),

    url(r'^nuevoAlumno/$',nuevoAlumno.as_view(), name='nuevoAlumno'),
    url(r'^verAlumno', verAlumno, name='verAlumno'),
    url(r'^info/(?P<id>\d+)/$',Informacion),
    url(r'^NewAntecedente/$', NewAntecedente),
    url(r'^VerAntecedente/$', VerAntecedente),
    url(r'^buscarAlumno/$', buscarAlumno),
    url(r'^escogido/(?P<id>\d+)/$', escogido),
    url(r'^misAntecedentes/(?P<id>\d+)/$', VerAntecedente),
    url(r'^verHistorial/(?P<id>\d+)/$', verHistorial),
    url(r'^Darbaja/(?P<id>\d+)/$', Darbaja),
    url(r'^DarAlta/(?P<id>\d+)/$', DarAlta),
    url(r'^AltaAlumno/(?P<id>\d+)/$', AltaAlumno),
    url(r'^AlumnoVerDaja/(?P<id>\d+)/$', Darbaja),
    url(r'^DelAlumno/(?P<id>\d+)/$', DelAlumno),
    url(r'^AlumnoVerAlta/(?P<id>\d+)/$', DarAlta),
    url(r'^EditAlumno/(?P<id>\d+)/$', EditAlumno),
    url(r'^BajaAntecedente/(?P<id>\d+)/$', BajaAntecedente),
    url(r'^DelAntecedentes/(?P<id>\d+)/$', DelAntecedentes),
    url(r'^AltaAntecedente/(?P<id>\d+)/$', AltaAntecedente),
    url(r'^bajaAntecendetes/(?P<id>\d+)/$', bajaAntecendetes),
    url(r'^editAnte/(?P<id>\d+)/$', editAnte),
    url(r'^DarbajaDocente/(?P<id>\d+)/$', DarbajaDocente),
    url(r'^Deletedocente/(?P<id>\d+)/$', Deletedocente),
    url(r'^DarAltaDocente/(?P<id>\d+)/$', DarAltaDocente),
    url(r'^Altadocentes/(?P<id>\d+)/$', Altadocentes),
    url(r'^Canbiodirector/(?P<id>\d+)/$', Canbiodirector),
    url(r'^buscar/$', buscar),
    url(r'^nuevoAlumnoA/$', nuevoAlumnoA),
    url(r'^verHistoriales/$', verHistoriales),
    url(r'^por_curso/$', por_curso),
)

braun/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'braun.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include("braun.apps.inicio.urls")),

    url(r'^media/(?P<path>.*)$','django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}
        ),

)

braun/apps/inicio/models.py
#encoding:utf-8
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.forms import User
# Create your models here.
class Perfiles(models.Model):
	usuario = models.OneToOneField(User, unique=True, related_name='perfil')
	materno = models.CharField(max_length=50)
	ci = models.IntegerField()
	telefono = models.IntegerField()
	def __unicode__(self):
		return self.usuario.username
class Bismestre(models.Model):
	bimestre = models.IntegerField()
	titulo = models.CharField(max_length=50)
	descripcion = models.TextField(blank=True, null=True)
	archivo = models.FileField(upload_to = 'bimestres')
	docente = models.ForeignKey(User)
	fecha_registro=models.DateTimeField(auto_now=True)
	estado = models.BooleanField(default=True)
	def __unicode__(self):
		return self.titulo
class Avanse(models.Model):
	titulo = models.CharField(max_length=50)
	descripcion = models.TextField(blank=True, null=True)
	materia = models.CharField(max_length=50)
	docente = models.ForeignKey(User)
	archivo = models.FileField(upload_to = 'avanses')
	estado = models.BooleanField(default=True)
	fecha_registro=models.DateTimeField(auto_now=True)
	def __unicode__(self):
		return self.titulo
class Curso(models.Model):
	usuario = models.ForeignKey(User)
	curso = models.CharField(max_length=50)
	fecha_registro=models.DateTimeField(auto_now=True)
	estado=models.BooleanField(default=True)
	def __unicode__(self):
		return self.curso

class Alumnos(models.Model):
	usuario = models.OneToOneField(User, unique=True, related_name='perfilAlumno')
	materno = models.CharField(max_length=50)
	curso = models.ForeignKey(Curso)
	ci = models.IntegerField(blank=True,null=True)
	telefono = models.IntegerField(blank=True,null=True)
	def __unicode__(self):
		return "%s"%(self.ci)
class Directores(models.Model):
	usuario = models.OneToOneField(User, unique=True, related_name='perfilDirector')
	materno = models.CharField(max_length=50)
	ci = models.IntegerField()
	telefono = models.IntegerField()
	def __unicode__(self):
		return self.usuario.username
class antecedentes(models.Model):
	usuario=models.ForeignKey(User)
	alumno=models.ForeignKey(Alumnos)
	asunto=models.CharField(max_length=50)
	descripcion=models.TextField()
	fecha_registro=models.DateTimeField(auto_now=True)
	estado=models.BooleanField(default=True)
	def __unicode__(self):
		return self.alumno.materno

braun/apps/inicio/views.py
#encoding:utf-8
from django.shortcuts import render, render_to_response
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, context
from django.contrib.auth.forms import User
from .forms import *#aki estoy importando todos mis formularios de mi achivo form.py
from .models import *##aki estoy importando todos mis models de mi achivo models.py
# Create your views here.
from django.views.generic import TemplateView, FormView,ListView,CreateView
from django.core.urlresolvers import reverse_lazy
import datetime
import calendar
from django.db.models import Q
import StringIO
from xhtml2pdf import pisa
from django.template.loader import render_to_string
from datetime import datetime, date, time, timedelta

# Create your views here.
def inicio(request):
	return render(request,'inicio/inicio.html')

def loguin(request):
	if not request.user.is_anonymous():
		return HttpResponseRedirect('/privado/')
	if request.method=='POST':
		print "has escho POST"
		formulario=AuthenticationForm(request.POST)
		if formulario.is_valid:
			usuario=request.POST['name']
			print usuario
			clave=request.POST['password']
			print clave
			acceso=authenticate(username=usuario,password=clave)
			if acceso is not None:
				if acceso.is_superuser:
					login(request,acceso)
					return HttpResponse('/privado/')
				else:
					if acceso.is_staff:
						login(request,acceso)
						return HttpResponse('/privado/')
					else:
						if acceso.is_active:
							login(request,acceso)
							return HttpResponseRedirect('/privado/')
						else:
							return HttpResponse("Error, Usuario o contraseña incorrecta.")
			else:
				return HttpResponse("Error, Usuario o contraseña incorrecta.")
	else:
		formulario=AuthenticationForm()
	return render(request,'inicio/loguin.html')
@login_required(login_url='/')
def privado(request):
	now = datetime.now()
	if request.user.is_superuser:
		return render(request,'administrador/admin.html',{'now':now},context_instance=RequestContext(request))
	else:
		#user.is_staff decimoe q el administrador le dio el permiso para subsustema secretria
		if request.user.is_staff:
			return render(request,'administrador/admin.html',{'now':now},context_instance=RequestContext(request))
		else:
			if request.user.is_active:
				return render(request,'inicio/inicio.html',{'now':now},context_instance=RequestContext(request))
			else:
				return HttpResponseRedirect('/salir/')

@login_required(login_url='/')
def salir(request):
	logout(request)
	return HttpResponseRedirect('/')

@login_required(login_url='/')
def editar_perfil(request):
	if request.method=='POST':
		user_form=UserForms(request.POST,instance=request.user)
		#perfil_form=formPerfiles(request.POST,instance=request.user.perfilDirector)
		try:
			perfil_form=formPerfiles(request.POST,instance=request.user.perfilDirector)
			print "Director: ",perfil_form
			if user_form.is_valid() and perfil_form.is_valid():
				user_form.save()
				perfil_form.save()
				return HttpResponse("Actualizaste tus Datos correctamente.")
		except:
			perfil_form=formPerfiles(request.POST,instance=request.user.perfil)
			if user_form.is_valid() and perfil_form.is_valid():
				user_form.save()
				perfil_form.save()
				return HttpResponse("Actualizaste tu Datos correctamente.")
	else:
		user_form=UserForms(instance=request.user)
		perfil_form=""
		try:
			perfil_form=formPerfiles(instance=request.user.perfilDirector)
		except:
			perfil_form=formPerfiles(instance=request.user.perfil)
	return render_to_response('inicio/datosPerfil.html',{'user_form':user_form,'perfil_form':perfil_form},context_instance=RequestContext(request))
class nuevoUser(FormView):
	template_name = 'inicio/nuevo.html'
	form_class=UserForm
	success_url = reverse_lazy('listaUsuarios')
	def form_valid(self,form):
		user=form.save()
		perfil=Perfiles()
		perfil.usuario = user
		perfil.materno=form.cleaned_data['materno']
		perfil.ci=form.cleaned_data['ci']
		perfil.telefono=form.cleaned_data['telefono']
		perfil.save()
		return super(nuevoUser, self).form_valid(form)

class nuevoDirector(FormView):
	template_name = 'administrador/nuevoDirector.html'
	form_class=UserFormDirector
	success_url = reverse_lazy('verDitectores')
	def form_valid(self,form):
		user=form.save()
		perfil=Directores()
		perfil.usuario = user
		perfil.materno=form.cleaned_data['materno']
		perfil.ci=form.cleaned_data['ci']
		perfil.telefono=form.cleaned_data['telefono']
		perfil.save()
		return super(nuevoDirector, self).form_valid(form)

######hacer una consulta para optener todos los cursos
class nuevoAlumno(FormView):
	template_name = 'administrador/nuevoAlumno.html'
	form_class=UserFormAlumno
	success_url = reverse_lazy('verAlumno')
	def form_valid(self,form):
		user=form.save()
		perfil=Alumnos()
		perfil.usuario = user
		perfil.materno=form.cleaned_data['materno'].capitalize()
		#perfil.curso.form.cleaned_data['curso']
		perfil.ci=form.cleaned_data['ci']
		perfil.telefono=form.cleaned_data['telefono']
		perfil.save()
		return super(nuevoAlumno, self).form_valid(form)

def nuevoAlumnoA(request):
	cursos = Curso.objects.all()
	print "principal"
	if request.method=="POST":
		form=Alumnoforms(request.POST)
		if(form.is_valid()):
			alumno=User()
			alumno.password=request.POST['password']
			alumno.username=request.POST['username']
			alumno.first_name=request.POST['first_name']
			alumno.last_name=request.POST['last_name']
			alumno.email=request.POST['email']
			alumno.save()
			#form.save()
			objeto = alumno.save()
			print "ultimo id Registrado",alumno.id
			perfil=Alumnos()
			perfil.usuario_id = alumno.id
			perfil.materno=request.POST['materno']
			perfil.curso_id=int(request.POST['curso'])
			perfil.ci=int(request.POST['ci'])
			perfil.telefono=int(request.POST['telefono'])

			perfil.save()
			return HttpResponseRedirect("/escogido/%s/"%(alumno.id))
	form=Alumnoforms()
	Perfil = formPerfil()
	return render_to_response('administrador/nuevoAlumno.html',{"form":form,'Perfil':Perfil,'cursos':cursos},RequestContext(request))
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
def verHistoriales(request):
	historiales = antecedentes.objects.filter(estado=True).order_by("-id")
	t_his = antecedentes.objects.filter(estado=True).count()
	alumnos = Alumnos.objects.all().order_by("-id")
	usuarios = User.objects.filter(is_active=True).order_by("-id")
	cursos=Curso.objects.filter(estado=True)
	paginator=Paginator(historiales,20)
	page = request.GET.get('page')
	try:
		contenido = paginator.page(page)
	except PageNotAnInteger:
		contenido = paginator.page(1)
	except EmptyPage:
		contenido = paginator.page(paginator.num_pages)
	return render_to_response('administrador/verHistorial.html',{'cursos':cursos,'alumnos':alumnos,'usuarios':usuarios,'contenido':contenido,'historiales':contenido,'t_his':t_his},context_instance=RequestContext(request))
def verDitectores(request):
	users=User.objects.all().order_by("-id")
	perfil=Directores.objects.all().order_by("-id")
	t_user=Directores.objects.all().count()
	return render_to_response("administrador/DatosDirectores.html",{'users':users,'perfil':perfil,'t_user':t_user},context_instance=RequestContext(request))

def verAlumno(request):
	users=User.objects.filter(is_staff=False,is_superuser=False).order_by("-id")
	t_user=User.objects.filter(is_staff=False,is_superuser=False).count()
	paginator=Paginator(users,20)
	page = request.GET.get('page')
	try:
		contenido = paginator.page(page)
	except PageNotAnInteger:
		contenido = paginator.page(1)
	except EmptyPage:
		contenido = paginator.page(paginator.num_pages)
	return render_to_response("administrador/verAlumno.html",{'users':contenido,'contenido':contenido,'t_user':t_user},context_instance=RequestContext(request))
def DatosUsuario(request):
	users=User.objects.all().order_by("-id")
	perfil=Perfiles.objects.all().order_by("-id")
	t_user=Perfiles.objects.all().count()
	return render_to_response("inicio/DatosUsuario.html",{'users':users,'perfil':perfil,'t_user':t_user},context_instance=RequestContext(request))
def verificacion(request):
	use=request.GET['use']
	try:
		us=User.objects.get(username=use)
		return HttpResponse("El Nombre de Usuario %s, ya existe Intente con otro Nombre."%(us))
	except User.DoesNotExist:
		return HttpResponse()
def PlanBimestral(request):
	if request.method=='POST':
		Usuario=Bismestre(docente=request.user)
		forms = FormBimestre(request.POST,request.FILES,instance=Usuario)
		if forms.is_valid():
			forms.save()
			message = "Los datos de registraron correctamente!"
	else:
		forms = FormBimestre()
	return render(request,'inicio/PlanBimestral.html',{'forms':forms},context_instance=RequestContext(request))
def newAvanse(request):
	if request.method=="POST":
		Usuario=Avanse(docente=request.user)
		forms = FormAvanse(request.POST,request.FILES,instance=Usuario)
		if forms.is_valid():
			forms.save()
			message = "Los datos de registraron correctamente!"
	else:
		forms = FormAvanse()
	return render(request,'inicio/newAvanse.html',{'forms':forms},context_instance=RequestContext(request))

def verPlanBimestral(request):
	bimestres = Bismestre.objects.all().order_by("-id")
	t_b = Bismestre.objects.all().count()
	return render(request,'inicio/verPlanBimestral.html',{'bimestres':bimestres,'t_b':t_b},context_instance=RequestContext(request))
def verAvances(request):
	avanses = Avanse.objects.all().order_by("-id")
	t_a = Avanse.objects.all().count()
	return render(request,'inicio/verAvances.html',{'avanses':avanses,'t_a':t_a},context_instance=RequestContext(request))
def docentes(request):
	director=User.objects.filter(is_superuser=True).order_by("-id")
	dire=Directores.objects.all().order_by("-id")[0:1]
	for i in director:
		for j in dire:
			if j.usuario.id == i.id:
				print "director:",i.username

braun/templates/inicio/DarAlta.html
<label>Esta Seguro dar de Alta al Usuario: <br>
	<strong>{{dato.get_full_name|upper}} {{dato.perfilAlumno.materno|upper}}</strong>
	 </label>

 <div class="modal-footer">
    <button class="btn btn-danger" type="button" onclick="AltaAluno();">Confirmar</button>
  </div>
<script type="text/javascript">
function AltaAluno(){
	$.ajax({
		type:'GET',
		url:'/AltaAlumno/'+{{dato.id}}+'/',
		success:function(resp){
			$("#DatosContenidos").html(resp);
			Update();
		}
	});
}
function Update(){
	$.ajax({
		type:'GET',
		url:'/escogido/'+{{dato.id}}+'/',
		success:function(resp){
			$("#FormAjax").html(resp);
		}
	});
}
</script>

braun/templates/inicio/Darbaja.html
<label>Esta Seguro dar de baja al Alumno: <br><strong>{{dato.get_full_name|upper}} {{dato.perfilAlumno.materno|upper}}</strong>
	 </label>

 <div class="modal-footer">
    <button class="btn btn-danger" type="button" onclick="Delalumnos();">Confirmar</button>
  </div>
  <script type="text/javascript">
function Delalumnos(){
	$.ajax({
		type:'GET',
		url:'/DelAlumno/'+{{dato.id}}+'/',
		success:function(resp){
			$("#DatosContenidos").html(resp);
			Update();
		}
	});
}
function Update(){
	$.ajax({
		type:'GET',
		url:'/escogido/'+{{dato.id}}+'/',
		success:function(resp){
			$("#FormAjax").html(resp);
		}
	});
}
  </script>

braun/templates/inicio/DarbajaDocente.html
<label>Esta Seguro dar de baja al Profesor: <br>
	<strong>{{dato.get_full_name|upper}} {{dato.perfil.materno|upper}}</strong>
</label>
 <div class="modal-footer">
    <button class="btn btn-danger" type="button" onclick="DelDocente();">Confirmar</button>
  </div>
  <script type="text/javascript">
function DelDocente(){
	$.ajax({
		type:'GET',
		url:'/Deletedocente/'+{{dato.id}}+'/',
		success:function(resp){
			$("#DatosContenidos").html(resp);
			DatosUser();
		}
	});
}
  </script>

braun/templates/inicio/DatosUsuario.html
<div class="table-responsive">
<table class="table table-hover table-striped">
	<tr><td colspan="10" align="center">LISTA DE DOCENTES EN EL SISTEMA</td></tr>
		<tr class="success">
			<td>Usuario</td>
			<td>Nombre</td>
			<td>Ap. Paterno</td>
			<td>Ap. Materno</td>
			<td>Nro. CI.</td>
			<td>E-mail</td>
			<td>Teléfono</td>
			<td>Fecha y hora de registro</td>
			<td>Estado</td>
		</tr>
{% for j in users %}
	{% for i in perfil %}
			{% if j.id == i.usuario_id %}
<tr>
	<td>{{j.username}}</td>
	<td>{{j.first_name|upper}}</td>
	<td>{{j.last_name|upper}}</td>
	<td>{{i.materno|upper}}</td>
	<td>{{i.ci}}</td>
	<td>{{j.email}}</td>
	<td>{{i.telefono}}</td>
	<td>{{j.date_joined}}</td>
	<td>
	{% if user.is_superuser %}
		{% if j.is_staff %}
				<span><a href="#" onclick="DarbaDocente({{j.id}})" data-toggle="modal" data-target="#exampleModal"><img src="/static/img/icon_success.gif"></a></span>
			{% else %}
				<span><a href="#" onclick="AltaDocente({{j.id}});" data-toggle="modal" data-target="#exampleModal"><img src="/static/img/icon_error.gif"></a></span>
		{% endif %}
	{% else %}
			<span class="glyphicon glyphicon-info-sign"></span>
	{% endif %}
	</td>
</tr>
		{% endif %}
	{% endfor %}
{% endfor %}
	<tr>
		<td>Usuarios:{{t_user}}</td>
	</tr>
	</table>
</div>
<script type="text/javascript">
function DarbaDocente(ids){
	$.ajax({
			type:'GET',
			url:'/DarbajaDocente/'+ids+'/',
			success:function(resp){
				$("#DatosContenidos").html(resp);
			}
		});	
}
function AltaDocente(ids){
	$.ajax({
			type:'GET',
			url:'/DarAltaDocente/'+ids+'/',
			success:function(resp){
				$("#DatosContenidos").html(resp);
			}
		});	
}
</script>

braun/templates/inicio/NewAnteRegistro.html
<script type="text/javascript">
    $(function(){
        $('#Tipo').submit(function(e){
        e.preventDefault();
        var dato=
        console.log(dato);
        $.ajax({
            type:'POST',
            url:'/NewAntecedente/',
            data: dato,
            success:function(resp){
                $(".modal-body").html(resp);
                VerAntecedente();
            }
        });
    });
    });
</script>
<div class="card">
    <strong>Registrar Nuevo Avanse de Materia</strong><br>
    <span>Todos los datos con requeridos (*)</span>
 <form method="POST" id="Tipo" enctype="multipart/form-data"> {% csrf_token %}
                {{forms}}<br>
    <button class="btn btn-success">Guardar</button>
  </form>
  <p id="valid" style="color:red; text_align:center;"></p>
</div> 

braun/templates/inicio/NewAntecedente.html
<style type="text/css">
    #busquedaFrol{width:800px;margin: auto;margin-top: 20px;}
    #busquedaFrol #buscarA{width: 500px;margin: auto;float: left;}
    #busquedaFrol #id_alumno{float: right;width: 300px;}
</style>
<div class="input-group custom-search-form" id="busquedaFrol">
<form action="/buscarAlumno/" method="post" id="buscarA" class="sidebar-form">
    {% csrf_token %}
<div class="input-group">

 <label>Busque un Estudiante:</label> <input type="text" name="alumno" id="id_alumno" class="form-control" title=" Buscar Trabajador" placeholder="Nombre, Apellido, Ci," required>
      <span class="input-group-btn">
<button type="submit" name="search" id="search-btn" class="btn btn-flat"><span class="glyphicon glyphicon-search"></span>
        </button>
      </span>
</div>
</form>
</span>
</div>
<script type="text/javascript">
$(document).ready(Sheart);
    function Sheart(){ 
      var tbuscar=$("#id_alumno").attr('autocomplete','off');
      tbuscar.keypress(buscar);
  }
  function buscar(){
    $.ajax({
        type:'GET',
        url:'/buscarAlumno/',
        data:$("#buscarA").serialize(),
        success:resultado,
        error:errores
    });
    console.log($("#buscarA").serialize());
}
function resultado(data){
    $("#DatosAjax").fadeIn("slow");
    console.log(data);
    $("#DatosAjax").html(data);
}
function errores(){
    alert ("Error");
}
$("#buscarA").on("submit",function(e){
        e.preventDefault();
        var datos=$(this).serialize();
        //alert(datos);
          $.ajax({
              type:"POST",
              url:"/buscarAlumno/",
              data:datos,
              success:function(resp){
                $(".resultados").fadeIn("slow");
                //alert(resp);
                $("#DatosAjax").html(resp);
                
              }
          });
      });
</script>

braun/templates/inicio/VerAntecedente.html
<div class="table-responsive">
	<table class="table table-hover table-striped">
		<tr class="success">
			<td>Cod</td>
			<td>Asunto</td>
			<td>Descripción</td>
			<td>Fecha y hora de registro</td>
			<td>Registrado por</td>
			<td>Estado</td>
			<td>Editar</td>
		</tr>
		{% for i in datos %}
		<tr>
			<td>{{i.id}}</td>
			<td>{{i.asunto|upper}}</td>
			<td>{{i.descripcion}}</td>
			<td>{{i.fecha_registro}}</td>
			<td>{{i.usuario.get_full_name|upper}}</td>
			{% if i.estado %}
			<td><span><a href="#" onclick="BajaInfo({{i.id}});" title="Dar de Baja" data-toggle="modal" data-target="#exampleModal"><img src="/static/img/icon_success.gif"></a></span></td>
			{% else %}
		<td><span><a href="#" onclick="AltaAntece({{i.id}});" title="Dar de Alta" data-toggle="modal" data-target="#exampleModal"><img src="/static/img/icon_error.gif"></a></span></td>
			{% endif %}
			<td>
				<a href="#" onclick="EditAntece({{i.id}});" title="Editar Informacion" data-toggle="modal" data-target="#exampleModal"><span class="glyphicon glyphicon-pencil"></span></a>
				<!-- <span class="glyphicon glyphicon-info-sign" title="No Tiene permisos"></span></a> -->
			</td>
		</tr>
		{% empty %}
		<tr>
			<td>No se Registró ningún historial para este alumno</td>
		</tr>
		{% endfor %}
		<tr><td></td><td>Registros: {{cont}}</td></tr>
	</table>
</div>
<script type="text/javascript">
function BajaInfo(ids){
	$.ajax({
		type:'GET',
		url:'/BajaAntecedente/'+ids+'/',
		success:function(resp){
			$("#DatosContenidos").html(resp);
		}
	});
}
function EditAntece(ids){
	$.ajax({
		type:'GET',
		url:'/editAnte/'+ids+'/',
		success:function(resp){
			$("#DatosContenidos").html(resp);
		}
	});
}
function AltaAntece(ids){
	$.ajax({
		type:'GET',
		url:'/AltaAntecedente/'+ids+'/',
		success:function(resp){
			$("#DatosContenidos").html(resp);
		}
	});
}
</script>

braun/templates/inicio/buscarAlumno.html
<script type="text/javascript">
	$(".aa p").on('click',Escogido);
	function Escogido(e){
		e.preventDefault();
		var ulrs=$(this).attr("href");
		//alert(ulrs);
		$.ajax({
			type:'GET',
			url:ulrs,
			success:function(resp){
				$("#DatosAjax").fadeOut(500);
				$("#FormAjax").html(resp);
			}
		});
	}
</script>
{% for i in resultados %}
<a class="aa"><p style="cursor: pointer;" href="/escogido/{{i.id}}/">Cod: {{i.id}}.- {{i.get_full_name|upper}} {{i.perfilAlumno.materno|upper}} - CI: {{i.perfilAlumno.ci}}</p></a>
{% empty %}
No hay Registros: <a href="#" onclick="NewAlumnos();"> <span class="glyphicon glyphicon-user"> </span>  Registrar Nuevo Alumno</a>
{% endfor %}

braun/templates/inicio/buscarHistorial.html
<script type="text/javascript">
	$(".aa p").on('click',Escogido);
	function Escogido(e){
		e.preventDefault();
		var ulrs=$(this).attr("href");
		//alert(ulrs);
		$.ajax({
			type:'GET',
			url:ulrs,
			success:function(resp){
				$("#DatosAjax").fadeOut(500);
				$("#FormAjax").html(resp);
			}
		});
	}
</script>
{% for i in resultados %}
<a class="aa"><p style="cursor: pointer;" href="/escogido/{{alumno.id}}/">Cod: {{i.id}}.- <strong>{{i.asunto|upper}}</strong>: {{i.descripcion}}</p></a>
	{% if i.estado %}
	{% else %}
	<strong>El registro esta en baja</strong>
	{% endif %}
{% empty %}
<a href="#">  <span class="glyphicon glyphicon-alert"> </span> No se encontraron registros</a>
{% endfor %}